# Generated by Django 5.0.4 on 2024-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
