# Generated by Django 4.2.11 on 2024-05-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='featured_image_url',
        ),
    ]
